dependencies:
  build:
    - flutter:1.20.1
    - android:latest
    - java:8.202.08
    
build_targets:
  - name: android
    commands:
      - flutter build appbundle
  - name: ios
    commands:
      - echo "iOS builds not implemented yet"

ci:
  builds:
    - name: android
      build_target: android
    - name: ios
      build_target: ios
