dependencies:
  build:
    - flutter:1.20.1
    - android:latest
    - java:8.202.08
    - python:3.8.5

build_targets:
  - name: android
    commands:
      - bash hydrate_keys.sh
      - flutter build appbundle # --build-number ??? --build-name `git describe --tags --abbrev=0 --exact-match || git rev-parse --short head`
  - name: ios
    commands:
      - echo "iOS builds not implemented yet"
  - name: release
    build_after:
      - android
      - ios
    commands:
      - git clone https://github.com/glacials/android-bundle-uploader
      - pip install -r android-bundle-uploader/requirements.txt
      - python android-bundle-uploader/main.py service-account-private-key.json io.splits ./build/app/outputs/bundle/release/app-release.aab beta

ci:
  builds:
    - name: android
      build_target: android
    - name: ios
      build_target: ios
    - name: release
      build_target: release
