dependencies:
  build:
    - flutter:1.20.1
    - androidsdk:latest

build_targets:
  - name: android
    commands:
      - sdkmanager --install tools
      - sdkmanager --install platform-tools
      - sdkmanager --install build-tools;28.0.3
      - sdkmanager --install platforms;android-28
      - sdkmanager --install system-images;android-28;default;x86_64
      - flutter build appbundle
  - name: ios
    commands:
      - echo "iOS builds not implemented yet"

ci:
  builds:
    - name: android
      build_target: android
      when: tagged is true
    - name: ios
      build_target: android
      when: tagged is true
