name: splitsio
description: The Splits.io mobile app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.6+16

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  cache_image: ^1.0.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^3.3.1+1
  oauth2_client: ^1.3.0
  sentry: ^3.0.0
  uni_links: ^0.2.0
  url_launcher: ^5.4.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.4"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#1a1c21"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: "Bukhari Script"
      fonts:
        - asset: "assets/fonts/Bukhari-Script.ttf"
    - family: "Bukhari Script Alternates"
      fonts:
        - asset: "assets/fonts/BukhariScriptAlternates.ttf"
